### ISSUE TITLE
entity are not available (after update to 2.0.0) [BUG]

### ISSUE THREAD

**Issue by YvesZH** [dmamontov/hass-ledfx#11]
My setup:
 - HASS version: 2022.7.6
 - Component version 2.0.0
 - LedFx version 0.10.7

After i updated your great tool (via HACS) to 2.0.0, all related new entity are not available:
![417B150E-0B0C-425F-8871-A608039C8FF2](https://user-images.githubusercontent.com/64573990/180862303-d5902fc4-fc78-47eb-9645-8ce728595ed3.jpeg)

Before i update, i delet the integration and reboot.
🤷🏻

**Comment by dmamontov** [comment]
@YvesZH Good afternoon. It's not a mistake. They are disabled by default, they all need to be enabled.

**Comment by YvesZH** [comment]
@dmamontov thanks
i tried already to activate like this:

![2239B253-5E58-4926-B7B1-1ED2A1BC6B1B](https://user-images.githubusercontent.com/64573990/180864138-1bfb73e7-4ba7-4f26-b11f-312b8e74ba5a.jpeg)

But it looks like that (first line):
![8B7DABEF-D80E-44F7-A173-26B095CD3388](https://user-images.githubusercontent.com/64573990/180864377-6de9934c-58d7-4939-bf84-61526339ea21.jpeg)

Sorry for my noobness 🙈

**Comment by dmamontov** [comment]
@YvesZH This is also normal. She is now UNAVAILABLE. After the effect is enabled, only those that are available for this effect will change their status.

**Comment by YvesZH** [comment]
@dmamontov sorry, i don't get it.
I stream over e131. I have to turn on the ledfx, so the the wled and hyperion device change automatic to the e131 input. If all entity are disable, i can't turn on ledfx over home-assistant.
In the last version was it essy posible. 🤷🏻

**Comment by dmamontov** [comment]
@YvesZH In previous versions, they also have the UNAVAILABLE status always until you turn them on. To be honest, I don’t understand your case to the end. Why include hyperion and ledfx together? I need more information.

P.S. Turning on through light works the same way)

**Comment by YvesZH** [comment]
@dmamontov sorry that i confused you.  in the previous version it generated a light entity for each device (light).  So I could e.g.  perform the following ha automation (action):
![70457DC9-A556-4F62-9C83-76977C180859](https://user-images.githubusercontent.com/64573990/180871836-3236e4d5-0c87-471b-93fc-997fe1cb2a95.jpeg)
after installing version 2.0.0 i can't find any more light entities

**Comment by dmamontov** [comment]
@YvesZH I finally understood you. Go not to objects but to devices and everything will be grouped there. or for example:

number.ledfx_192_168_31_122_garland_2_band_count = light.ledfx_192_168_31_122_garland_2

**Comment by dmamontov** [comment]
I made a similar generation on purpose. many had problems with uniqueness. Now everything is unique.

**Comment by YvesZH** [comment]
@dmamontov you mean this view:
![70402D8A-B569-4A9A-814B-389C8C798AF7](https://user-images.githubusercontent.com/64573990/180875316-0554517a-7237-4749-880d-ba68bb4bef77.jpeg)
I can't find any light entity there. And if i can't turn on, the other entity from your ledfx-integration are inactive.

**Comment by dmamontov** [comment]
@YvesZH But this is strange. Please provide [diagnostic information](https://www.home-assistant.io/integrations/diagnostics/). And are there any errors in the logs?

**Comment by YvesZH** [comment]
> @YvesZH But this is strange. Please provide [diagnostic information](https://www.home-assistant.io/integrations/diagnostics/). And are there any errors in the logs?

[config_entry-ledfx.txt](https://github.com/dmamontov/hass-ledfx/files/9184863/config_entry-ledfx.txt)

**Comment by YvesZH** [comment]
Yes 👏HA log:
![C6780CB7-4760-4101-A527-303302414D0E](https://user-images.githubusercontent.com/64573990/180878000-616b1d67-e432-4365-8ff7-7d88a72cadf4.jpeg)

**Comment by dmamontov** [comment]
@YvesZH https://github.com/dmamontov/hass-ledfx/releases/tag/v2.0.1

Update and check) And thanks for the error) Also, if it's not difficult, put an asterisk (you need to accumulate at least 100) and subscribe to my [telegram](https://t.me/hass_mamontov_tech) channel to be aware of all the updates)

**Comment by YvesZH** [comment]
Great 👏
It works like a charm. 
thanks a lot
And sorry, that i coudn't you point directly to the right error (i was a bit confused)

and yes, i give you the star. 🤩
