### ISSUE TITLE
No connection

### ISSUE THREAD

**Issue by steveof2620** [dmamontov/hass-ledfx#14]
Have LEDfx installed and running on a Mac. I can connect via an Ipad using the my mac's ip address. When entering the ip address and port on the integration I get ..
"There is no connection. Check if the data is correct"

**Comment by dmamontov** [comment]
@steveof2620 What version of ledfx? can you open it from another device?

**Comment by steveof2620** [comment]
Hello, I can open LEDfx from my iPad using my mac's IP address. I am running LEDfx backend 2.1.0 with frontend 2.0.0-beta50.
<img width="317" alt="Screen Shot 2022-08-28 at 10 17 59" src="https://user-images.githubusercontent.com/46661819/187052422-308d7416-a948-4ef6-a168-97ee166baef6.png">

**Comment by dmamontov** [comment]
@steveof2620 This version is still in beta and is not supported by the component. But the plans are to add support when it comes out of beta. At the moment, I see no reason to add support, maybe something is constantly changing in it.

**Comment by steveof2620** [comment]
No worries, that is understandable. Thanks for the feedback.

**Comment by dmamontov** [comment]
@steveof2620 Still added support for versions 2.x)

https://github.com/dmamontov/hass-ledfx/releases/tag/v2.1.0
