### ISSUE TITLE
Deprecated 'async_setup_platforms'

### ISSUE THREAD

**Issue by ocean75** [dmamontov/hass-ledfx#19]
Good day,

Receiving the following warning message in the HA logs. Anyone know how to update the integration? Thanks

```
Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for ledfx using this method at custom_components/ledfx/__init__.py, line 81: hass.config_entries.async_setup_platforms(entry, PLATFORMS)
```

**Comment by tungmeister** [comment]
@dmamontov can you have a look at this - looks like the integration will break in a few days when 2023.3 is released.

**Comment by dmamontov** [comment]
@ocean75, @tungmeister fixed in version https://github.com/dmamontov/hass-ledfx/releases/tag/v3.0.0

thanks
