### ISSUE TITLE
add http basic authentication support

### ISSUE THREAD

**Issue by pavax** [dmamontov/hass-ledfx#3]
Great addon! I protected my ledfx service instance using basic-authentation. could you also add this option as a configuration?

**Comment by dmamontov** [comment]
Yes, thanks, I will add such an opportunity

**Comment by dmamontov** [comment]
@pavax For a long time did not reach the hands. But I have added BasicAuth support https://github.com/dmamontov/hass-ledfx/releases/tag/v1.2.0
