### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by fabHAgithub** [dmamontov/hass-ledfx#5]
![image](https://user-images.githubusercontent.com/85220859/147984472-5da2034a-f210-4b01-9ce4-f3bfece55a32.png)
is this correct? can't login successful

**Comment by dmamontov** [comment]
доброго дня. а можно скрин вашего запущенного интерфейса вместе с url?

**Comment by fabHAgithub** [comment]
![image](https://user-images.githubusercontent.com/85220859/148141892-59f045e2-e5cd-4b75-927a-c046b7c00db1.png)
is this?
I'm using that programm on yellow circle.. is that correct?

**Comment by spiro-c** [comment]
`127.0.0.1` is your localhost ip address you need to use computer ip address like `192.168.xxx.yyy`
> ![image](https://user-images.githubusercontent.com/85220859/148141892-59f045e2-e5cd-4b75-927a-c046b7c00db1.png) is this? I'm using that programm on yellow circle.. is that correct?

**Comment by dmamontov** [comment]
I confirm, the fact is that you specify the local ip of the machine, and not the external one inside the network.
