### ISSUE TITLE
Example Lovelace card not working?

### ISSUE THREAD

**Issue by commodapse0q** [dmamontov/hass-ledfx#8]
Hi there!

I've gotten everything seemingly set up but im running into an issue. The lovelace card I cannot get to work for the life of me. (Not sure what the issue is, I am also new to HA)

https://imgur.com/a/p91xES0

Thanks for the help!

**Comment by commodapse0q** [comment]
Ok so I figured out the turning on/off streaming to each set of WLED's that I have, (Was confused as the WLED instances have the same names, so I failed to understand which one is for which, my mistake!)

**Comment by dmamontov** [comment]
@commodapse0q 
I think you should wait for the new version of the component, I am now actively putting it in order (I am developing it from scratch). I think in a week or two I will roll it out.

**Comment by commodapse0q** [comment]
Sounds good! Thank you for working on this, there is one other implementation I saw running the whole thing (ledfx) on HA but I've got quite the huge array of LEDs and need the performance to be separate from my HA instance.

Thanks again!

**Comment by dmamontov** [comment]
@commodapse0q https://github.com/dmamontov/hass-ledfx/releases/tag/v2.0.0

Issued a release.
